export const viniRossi = [
    {
        name: "Cellaia Rosso",
        description: "Cilento DOP, Aglianico, Barbera, Piedirosso, 12.5%, 2020",
        producer: "Azienda Agricola Marino",
        location: "Agropoli",
        tags: "vegan, bio", // Example: "vegan, no-sulfites, bio"    For no tags: ""
        glass: "7",         // For no glass: ""
        bottle: "20",
    },
    {
        name: "Caos",
        description: "Vino Rosso, 12 varietà diverse, 14%, 2020",
        producer: "Azienda Agricola Antonio Bianco",
        location: "Gioi",
        tags: "no-sulfites",
        glass: "7",
        bottle: "20",
    },
    {
        name: "Colle Arenario",
        description: "Cilento DOC, Aglianico, 13%, 2020",
        producer: "Tenuta Passaro",
        location: "Castellabate",
        tags: "",
        glass: "7",
        bottle: "22",
    },
    {
        name: "Donnaluna Rosso",
        description: "Cilento DOP, Aglianico, 14%, 2020",
        producer: "Viticoltori De Conciliis",
        location: "Prignano",
        tags: "bio",
        glass: "10",
        bottle: "26",
    },
    {
        name: "Rosso Campania",
        description: "Campania IGP, Aglianico, Cabernet sauvignon, 13%, 2021",
        producer: "Azienda Agricola Tredaniele",
        location: "Trentinara",
        tags: "",
        glass: "9",
        bottle: "30",
    },
    {
        name: "Malabrocca",
        description: "Paestum IGP, Aglianico, Camaiola, 12.5%, 2022",
        producer: "Azienda Agricola Salvatore Magnoni",
        location: "Rutino",
        tags: "no-sulfites",
        glass: "10",
        bottle: "31",
    },
    {
        name: "Patrinus",
        description: "Paestum IGT, Aglianico, Primitivo, 14%, 2021",
        producer: "Azienda Agricola Alferio Romito",
        location: "Castellabate",
        tags: "bio",
        glass: "10",
        bottle: "32",
    },
    {
        name: "Klèos",
        description: "Cilento DOP, Aglianico, 14%, 2021",
        producer: "Azienda Agricola Luigi Maffini",
        location: "Giungano",
        tags: "",
        glass: "10",
        bottle: "34",
    },
    {
        name: "Rosso Del Ciglio",
        description: "Paestum IGP, Aglianico, 14.5%, 2020",
        producer: "Azienda Agricola Salvatore Magnoni",
        location: "Rutino",
        tags: "no-sulfites, bio",
        glass: "12",
        bottle: "34",
    },
    {
        name: "Rosso Paestum",
        description: "Paestum IGP, Cabernet Sauvignon, Aglianico, 13.5%, 2018",
        producer: "Azienda Agricola Tredaniele",
        location: "Trentinara",
        tags: "",
        glass: "",
        bottle: "38",
    },
    {
        name: "Proclamo Riserva",
        description: "Cilento DOP, Aglianico, 15%, 2014",
        producer: "Azienda Agricola Marino",
        location: "Agropoli",
        tags: "",
        glass: "",
        bottle: "48",
    },
    {
        name: "Primalaterra 2012",
        description: "Cilento DOP, Aglianico, 16%, 2012",
        producer: "Azienda Agricola Salvatore Magnoni",
        location: "Rutino",
        tags: "",
        glass: "",
        bottle: "75",
    },
];

export const viniBianci = [
    {
        name: "Cellaia Bianco",
        description: "Cilento DOP, Fiano, Malvasia, 12.5%, 2022",
        producer: "Azienda Agricola Marino",
        location: "Agropoli",
        tags: "vegan, bio", // Example: "vegan, no-sulfites, bio"    For no tags: ""
        glass: "7",    // For no glass: ""
        bottle: "20",
    },
];