export const beers = [
    {
        name: "Unachiara",
        description: "Helles, 33 cl. vol. 5.2%",
        image: "",
        producer: "Birrificio Fieij",
        location: "Castelnuovo Cilento",
        tags: "",
        glass: "",
        bottle: "",
        location: "",
        price: "5",
        available: "yes", // for no: "no"
    },
    {
        name: "Unafresca",
        description: "Hefe-Weizen, 33 cl. vol. 5.5%",
        image: "",
        producer: "Birrificio Fieij",
        location: "Castelnuovo Cilento",
        tags: "",
        glass: "",
        bottle: "",
        location: "",
        price: "5",
        available: "yes",
    },
    {
        name: "Unambrata",
        description: "American Pale Ale, 33 cl. vol. 6%",
        image: "",
        producer: "Birrificio Fieij",
        location: "Castelnuovo Cilento",
        tags: "",
        glass: "",
        bottle: "",
        location: "",
        price: "5",
        available: "yes",
    },
    {
        name: "Unaspecial",
        description: "Belgian Dark Ale, 33 cl. vol. 6%",
        image: "",
        producer: "Birrificio Fieij",
        location: "Castelnuovo Cilento",
        tags: "",
        glass: "",
        bottle: "",
        location: "",
        price: "5",
        available: "yes",
    },
    {
        name: "Unaforte",
        description: "Belgian Strong Ale, 33 cl. vol. 8.5%",
        image: "",
        producer: "Birrificio Fieij",
        location: "Castelnuovo Cilento",
        tags: "",
        glass: "",
        bottle: "",
        location: "",
        price: "5",
        available: "yes",
    },
];

export const drinks = [
    {
        name: {
            it: "Acqua Microfiltrata",
            en: "Microfiltered Water",
        },
        description: {
            it: "Sistema Culligan, 75 cl",
            en: "Culligan System, 75 cl",
        },
        image: "",
        producer: "",
        tags: "",
        glass: "",
        bottle: "",
        location: "",
        price: "2",
        available: "yes",
    },
    {
        name: "Cedrata Tassoni",
        description: {
            it: "Storica bibita italiana del 1956. Bevanda analcolica frizzante, dolce ma con una punta di aspro.",
            en: "Historic Italian soda from 1956. Non-alcoholic sparkling drink, sweet but with a hint of sourness to it.",
        },
        image: "",
        producer: "",
        tags: "",
        glass: "",
        bottle: "",
        location: "",
        price: "3",
        available: "yes",
    },
    {
        name: "Mir-tonic",
        description: {
            it: "Una nuova idea di Gin. 100% made in Cilento.",
            en: "A new take on Gin. 100% made in Cilento.",
        },
        image: "",
        producer: "",
        tags: "",
        glass: "",
        bottle: "",
        location: "",
        price: "7",
        available: "yes",
    },
    {
        name: "Spritz",
        description: {
            it: "Classico cocktail italiano a base di vino.",
            en: "Classic Italian wine-based cocktail.",
        },
        image: "",
        producer: "",
        tags: "",
        glass: "",
        bottle: "",
        location: "",
        price: "7",
        available: "yes",
    },
    {
        name: {
            it: "Liquori artigianali",
            en: "Artisanal liqueurs",
        },
        description: {
            it: "La nostra selezione di liquori artigianali locali. Chiedeteci cosa è disponibile!",
            en: "Our selection of local handmade liqueurs. Ask us for what's available!",
        },
        image: "",
        producer: "",
        tags: "",
        glass: "",
        bottle: "",
        location: "",
        price: "4",
        available: "yes",
    },
    {
        name: "Amaro Di Sassano Penna",
        description: {
            it: "Amaro di erbe e radici. Produttore di 120 anni situato nel cuore del Cilento.",
            en: "Herbal and root bitter. 120-year-old producer located in the heart of Cilento.",
        },
        image: "",
        producer: "",
        tags: "",
        glass: "",
        bottle: "",
        location: "",
        price: "3",
        available: "yes",
    },
];