export const viniRossi = [
    {
        // Here it's not needed, but this is how you can have different text for en/it.
        name: {
            it: "Cellaia Rosso",
            en: "Cellaia Rosso",
        },
        description: Cilento DOP, Aglianico, Barbera, Piedirosso, 12.5%, 2020",
        producer: "Azienda Agricola Marino",
        location: "Agropoli",
        tags: "vegan, bio", // Example: "vegan, no-sulfites, bio"    For no tags: ""
        glass: "7",         // For no glass: ""
        bottle: "23",
    },
    {
        name: "Caos",
        description: "Vino Rosso, 12 varietà diverse, 14%, 2020",
        producer: "Azienda Agricola Antonio Bianco",
        location: "Gioi",
        tags: "no-sulfites",
        glass: "7",
        bottle: "20",
    },
    {
        name: "Colle Arenario",
        description: "Cilento DOC, Aglianico, 13%, 2020",
        producer: "Tenuta Passaro",
        location: "Castellabate",
        tags: "",
        glass: "7",
        bottle: "22",
    },
    {
        name: "Donnaluna Rosso",
        description: "Cilento DOP, Aglianico, 14%, 2020",
        producer: "Viticoltori De Conciliis",
        location: "Prignano",
        tags: "bio",
        glass: "10",
        bottle: "26",
    },
    {
        name: "Rosso Campania",
        description: "Campania IGP, Aglianico, Cabernet sauvignon, 13%, 2021",
        producer: "Azienda Agricola Tredaniele",
        location: "Trentinara",
        tags: "",
        glass: "9",
        bottle: "30",
    },
    {
        name: "Malabrocca",
        description: "Paestum IGP, Aglianico, Camaiola, 12.5%, 2022",
        producer: "Azienda Agricola Salvatore Magnoni",
        location: "Rutino",
        tags: "no-sulfites",
        glass: "10",
        bottle: "31",
    },
    {
        name: "Patrinus",
        description: "Paestum IGT, Aglianico, Primitivo, 14%, 2021",
        producer: "Azienda Agricola Alferio Romito",
        location: "Castellabate",
        tags: "bio",
        glass: "10",
        bottle: "32",
    },
    {
        name: "Klèos",
        description: "Cilento DOP, Aglianico, 14%, 2021",
        producer: "Azienda Agricola Luigi Maffini",
        location: "Giungano",
        tags: "",
        glass: "10",
        bottle: "34",
    },
    {
        name: "Rosso Del Ciglio",
        description: "Paestum IGP, Aglianico, 14.5%, 2020",
        producer: "Azienda Agricola Salvatore Magnoni",
        location: "Rutino",
        tags: "no-sulfites, bio",
        glass: "12",
        bottle: "34",
    },
    {
        name: "Rosso Paestum",
        description: "Paestum IGP, Cabernet Sauvignon, Aglianico, 13.5%, 2018",
        producer: "Azienda Agricola Tredaniele",
        location: "Trentinara",
        tags: "",
        glass: "",
        bottle: "38",
    },
    {
        name: "Proclamo Riserva",
        description: "Cilento DOP, Aglianico, 15%, 2014",
        producer: "Azienda Agricola Marino",
        location: "Agropoli",
        tags: "",
        glass: "",
        bottle: "48",
    },
    {
        name: "Primalaterra 2012",
        description: "Cilento DOP, Aglianico, 16%, 2012",
        producer: "Azienda Agricola Salvatore Magnoni",
        location: "Rutino",
        tags: "",
        glass: "",
        bottle: "75",
    },
];

export const viniBianci = [
    {
        name: "Cellaia Bianco",
        description: "Cilento DOP, Fiano, Malvasia, 12.5%, 2022",
        producer: "Azienda Agricola Marino",
        location: "Agropoli",
        tags: "vegan, bio", // Example: "vegan, no-sulfites, bio"    For no tags: ""
        glass: "7",         // For no glass: ""
        bottle: "20",
    },
    {
        name: "Colli Monticoricesi",
        description: "Bianco Campania, Fiano, Falanghina, 13%, 2022",
        producer: "Azienda Agricola Le Grazie",
        location: "Montecorice",
        tags: "",
        glass: "7",
        bottle: "20",
    },
    {
        name: "Etèl",
        description: "Campania IGP, Falanghina, 13%, 2022",
        producer: "Azienda Agricola Albamarina",
        location: "Foria di Centola",
        tags: "",
        glass: "7",
        bottle: "21",
    },
    {
        name: "Ogliastro Marina",
        description: "Cilento DOC, Fiano, 13%, 2022",
        producer: "Tenuta Passaro",
        location: "Castellabate",
        tags: "",
        glass: "7",
        bottle: "22",
    },
    {
        name: "Valmezzana",
        description: "Cilento DOP, Fiano, 14%, 2022",
        producer: "Azienda Agricola Albamarina",
        location: "Foria di Centola",
        tags: "",
        glass: "8",
        bottle: "24",
    },
    {
        name: "Proclamo",
        description: "Cilento DOP, Fiano, 13.5%, 2022",
        producer: "Azienda Agricola Marino",
        location: "Agropoli",
        tags: "vegan, bio",
        glass: "8",
        bottle: "24",
    },
    {
        name: "Vincenzì",
        description: "Campania IGP, Fiano, 12.5%, 2022",
        producer: "Azienda Agricola Le Grazie",
        location: "Montecorice",
        tags: "",
        glass: "8",
        bottle: "25",
    },
    {
        name: "Donnaluna Bianco",
        description: "Cilento DOC, Fiano, 13%, 2022",
        producer: "Viticoltori De Conciliis",
        location: "Prignano Cilento",
        tags: "bio",
        glass: "8",
        bottle: "26",
    },
    {
        name: "Corsole",
        description: "Campania IGP, Fiano, 13.5%, 2022",
        producer: "Azienda Agricola Tredaniele",
        location: "Trentinara",
        tags: "",
        glass: "10",
        bottle: "27",
    },
    {
        name: "Licosa",
        description: "Cilento DOC, Fiano, 13.5%, 2022",
        producer: "Azienda Agricola Alferio Romito",
        location: "Castellabate",
        tags: "bio",
        glass: "10",
        bottle: "32",
    },
    {
        name: "Kràtos",
        description: "Cilento DOP, Fiano, 13%, 2022",
        producer: "Azienda Agricola Luigi Maffini",
        location: "Giungano",
        tags: "",
        glass: "10",
        bottle: "34",
    },
    {
        name: "Vesole",
        description: "Campania IGP, Fiano, 12.5%, 2020",
        producer: "Azienda Agricola Tredaniele",
        location: "Trentinara",
        tags: "",
        glass: "",
        bottle: "38",
    },
];

export const viniRosati = [
    {
        name: "Maricinè",
        description: "Paestum IGP, Aglianico, 13.5%, 2022",
        producer: "Azienda Agricola Albamarina",
        location: "Foria di Centola",
        tags: "",    // Example: "vegan, no-sulfites, bio"    For no tags: ""
        glass: "7",  // For no glass: ""
        bottle: "22",
    },
    {
        name: "Anna",
        description: "Campania IGP, Pinot Nero, 13%, 2022",
        producer: "Azienda Agricola Tredaniele",
        location: "Trentinara",
        tags: "",
        glass: "10",
        bottle: "27",
    },
    {
        name: "Primmavera",
        description: "Paestum IGP, Aglianico, Camaiola, 13.5%, 2022",
        producer: "Azienda Agricola Salvatore Magnoni",
        location: "Rutino",
        tags: "",
        glass: "10",
        bottle: "31",
    },
];

export const viniVivaci = [
    {
        name: "Caprarizzo",
        description: "Paestum IGT, Greco, 11.5%, 2022",
        producer: "Azienda Agricola Caprarizzo",
        location: "Castellabate",
        tags: "",   // Example: "vegan, no-sulfites, bio"    For no tags: ""
        glass: "",  // For no glass: ""
        bottle: "22",
    },
    {
        name: "Pashkà",
        description: "Paestum Rosso IGP, Aglianico, Barbera, 12%, 2022",
        producer: "Azienda Agricola Casebianche",
        location: "Torchiara",
        tags: "bio",
        glass: "",
        bottle: "24",
    },
    {
        name: "Desiderio Bianco",
        description: "Campania IGT, Fiano, 13.5%, 2022",
        producer: "Azienda Agricola Alfonso Rotolo",
        location: "Rutino",
        tags: "",
        glass: "",
        bottle: "24",
    },
    {
        name: "Desiderio Rosato",
        description: "Aglianico Rosè Frizzante, Aglianico, 13%, 2022",
        producer: "Azienda Agricola Alfonso Rotolo",
        location: "Rutino",
        tags: "",
        glass: "",
        bottle: "26",
    },
];

export const viniSpumanti = [
    {
        name: "Selim",
        description: "Vino Spumante Brut, Aglianico, Fiano, 11.5%",
        producer: "Viticoltori De Conciliis",
        location: "Prignano Cilento",
        tags: "",   // Example: "vegan, no-sulfites, bio"    For no tags: ""
        glass: "9", // For no glass: ""
        bottle: "25",
    },
    {
        name: "Tredaniele Spumante",
        description: "Vino Spumante Brut Rosè, Pinot Nero, 12.5%",
        producer: "Azienda Agricola Tredaniele",
        location: "Trentinara",
        tags: "",
        glass: "",
        bottle: "37",
    },
];
